#!/usr/bin/env sh

git submodule update --init --recursive
cd zepto
npm install
npm run-script dist
cd ..

if [ -f index.js ]; then
  rm index.js;
fi

cat zepto/dist/zepto.js _amd_index.js > index.js
