#!/usr/bin/env sh

npm install https://github.com/mscienski/zepto@1.1.9
cd node_modules/zepto
npm install
npm run-script dist
cd ../..
cp -r node_modules/zepto ./zepto

if [ -f index.js ]; then
  rm index.js;
fi

cat zepto/dist/zepto.js _amd_index.js > index.js
