#!/usr/bin/env sh

npm install https://github.com/mscienski/zepto#v1.1.8
cd node_modules/zepto
npm install
npm run-script dist
cd ../..

if [ -f index.js ]; then
  rm index.js;
fi

cat node_modules/zepto/dist/zepto.js _index.js > index.js
